{{- $configsha := tpl (include "log4ham.config" .) . | sha256sum }}
{{- $configshamini := substr 0 8 $configsha }}
{{- $volumesha := tpl (toYaml .Values.volumes) . | sha256sum }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log4ham.fullname" . }}
  labels:
    {{- include "log4ham.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      component: service-pod
      {{- include "log4ham.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ $configsha }}
        checksum/volumes: {{ $volumesha }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: service-pod
        {{- include "log4ham.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log4ham.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: {{- include "log4ham.volumes" . | nindent 8 }}
      containers:
        - name: log4ham
          env: {{- include "log4ham.env" . | nindent 10 }}
          command: {{- .Values.command | toYaml | nindent 10 }}
          {{- with .Values.args }}
          args: {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts: {{- include "log4ham.volumeMounts" . | nindent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.be.image.repository }}:{{ .Values.be.image.tag | default  .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.be.image.pullPolicy }}
          ports:
            - name: http-health
              containerPort: 8079
              protocol: TCP
            - name: http-web
              containerPort: 8080
              protocol: TCP
          lifecycle: {{- toYaml .Values.be.lifecycle | nindent 12 }}

          # Suggest to NOT using startupProbe as it provides us no benefit here. AND detrimetally provides a fake positive start.
          {{- if .Values.be.startupProbe }}
          startupProbe: {{- toYaml .Values.be.startupProbe | nindent 12 }}
          {{- end }}
          livenessProbe: {{- toYaml .Values.be.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.be.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
