{{- if .Values.fe.enabled }}

{{- $root := . }}
{{- $newVal := dict "Values" .Values.fe "Files" .Files "Chart" .Chart "Release" .Release -}}
{{- with $newVal }}

{{- $volumesha := tpl (toYaml .Values.volumes) . | sha256sum }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log4ham.fullname" . }}-fe
  labels:
    component: frontend-pod
    {{- include "log4ham.labels" . | nindent 4 }}
spec:
  {{- if not $root.Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      component: frontend-pod
      {{- include "log4ham.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/volumes: {{ $volumesha }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: frontend-pod
        {{- include "log4ham.selectorLabels" . | nindent 8 }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log4ham.serviceAccountName" $root }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: {{- include "log4ham.volumes" . | nindent 8 }}
      containers:
        - name: log4ham
          env: {{- include "log4ham.env" . | nindent 12 }}
          command: {{- .Values.command | toYaml | nindent 12 }}
          {{- with .Values.args }}
          args: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: {{- include "log4ham.volumeMounts" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default  .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-web
              containerPort: 8080
              protocol: TCP
          lifecycle: {{- toYaml .Values.lifecycle | nindent 12 }}

          # Suggest to NOT using startupProbe as it provides us no benefit here. AND detrimetally provides a fake positive start.
          {{- if .Values.startupProbe }}
          startupProbe: {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}{{/* with */}}
{{- end }}
