---
hams:
  address: 0.0.0.0:8079
  prefix: hams
  checks:
    timeout: 5
    fails: 2
    preflights: []
    # - http://localhost:4201
    shutdowns: []
webservice:
  prefix:
    name: ham4log
    version: v0
  address: 0.0.0.0:8080
  forwarding_headers: []
persistence:
  db:
    pool_size: 10
    connection: {}
